//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Y_STR_Kit_UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Y_STR_Kit_UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///title Y-STR Kit 1.1
        ///
        ///REM     The MIT License (MIT)
        ///REM     Copyright © 2013-2015 Felix Immanuel
        ///REM     http://www.y-str.org
        ///REM     
        ///REM     Permission is hereby granted, free of charge, to any person obtaining a copy
        ///REM     of this software and associated documentation files (the Software), to deal
        ///REM     in the Software without restriction, including without limitation the rights
        ///REM     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///REM     copies of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string console_bam {
            get {
                return ResourceManager.GetString("console_bam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///title Y-STR Kit 1.1
        ///
        ///REM     The MIT License (MIT)
        ///REM     Copyright © 2013-2015 Felix Immanuel
        ///REM     http://www.y-str.org
        ///REM     
        ///REM     Permission is hereby granted, free of charge, to any person obtaining a copy
        ///REM     of this software and associated documentation files (the Software), to deal
        ///REM     in the Software without restriction, including without limitation the rights
        ///REM     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///REM     copies of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string console_vcf {
            get {
                return ResourceManager.GetString("console_vcf", resourceCulture);
            }
        }
    }
}
