//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Y_STR_Finder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Y_STR_Finder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&apos;empty-cells: hide; table-layout: auto;padding: 5x;border-spacing:5px;&apos;&gt;
        ///&lt;tr&gt;&lt;th  colspan=&apos;11&apos;&gt;Panel 1 (Y-DNA 1-12)&lt;/th&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b&gt;DYS393&lt;/b&gt;&lt;/td&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b&gt;DYS390&lt;/b&gt;&lt;/td&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b&gt;DYS19&lt;/b&gt;&lt;/td&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b&gt;DYS391&lt;/b&gt;&lt;/td&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b&gt;DYS385&lt;/b&gt;&lt;/td&gt;&lt;td width=&apos;100px&apos; style=&apos;text-align: center;&apos;&gt;&lt;b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ystr_overview {
            get {
                return ResourceManager.GetString("ystr_overview", resourceCulture);
            }
        }
    }
}
